apiVersion: 1

datasources:
  - name: Honeynet ClickHouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    database: honeynet
    isDefault: true
    editable: true
    jsonData:
      defaultDatabase: honeynet
      usePOST: true
      timeout: 10
    basicAuth: false
    # Uncomment and configure if ClickHouse requires authentication
    # basicAuthUser: ${CLICKHOUSE_USER}
    # secureJsonData:
    #   basicAuthPassword: ${CLICKHOUSE_PASSWORD}
